name: Test

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: docker-practice/actions-setup-docker@master
      - run: npm ci
      - run: npm test
